/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class uk_ac_manchester_tornado_drivers_opencl_natives_NativeCommandQueue */

#ifndef _Included_uk_ac_manchester_tornado_drivers_opencl_natives_NativeCommandQueue
#define _Included_uk_ac_manchester_tornado_drivers_opencl_natives_NativeCommandQueue
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     uk_ac_manchester_tornado_drivers_opencl_natives_NativeCommandQueue
 * Method:    mapOnDeviceMemoryRegion
 * Signature: (JJ)J
 */
JNIEXPORT jlong JNICALL Java_uk_ac_manchester_tornado_drivers_opencl_natives_NativeCommandQueue_mapOnDeviceMemoryRegion
(JNIEnv *, jclass, jlong, jlong);

/*
 * Class:     uk_ac_manchester_tornado_drivers_opencl_natives_NativeCommandQueue
 * Method:    mapOnDeviceMemoryNDRegion
 * Signature: (JJJJIJJJ)J
 */
JNIEXPORT jlong JNICALL
Java_uk_ac_manchester_tornado_drivers_opencl_natives_NativeCommandQueue_mapOnDeviceMemoryNDRegion
(JNIEnv *, jclass, jlong, jlong, jlong, jlong, jint, jlong, jlong, jlong);

#ifdef __cplusplus
}
#endif
#endif
