/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class uk_ac_manchester_tornado_drivers_spirv_ocl_SPIRVOCLNativeDispatcher */

#ifndef _Included_uk_ac_manchester_tornado_drivers_spirv_ocl_SPIRVOCLNativeDispatcher
#define _Included_uk_ac_manchester_tornado_drivers_spirv_ocl_SPIRVOCLNativeDispatcher
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     uk_ac_manchester_tornado_drivers_spirv_ocl_SPIRVOCLNativeDispatcher
 * Method:    clCreateProgramWithIL_native
 * Signature: (J[B[J[I)J
 */
JNIEXPORT jlong JNICALL Java_uk_ac_manchester_tornado_drivers_spirv_ocl_SPIRVOCLNativeDispatcher_clCreateProgramWithIL_1native
        (JNIEnv *, jobject, jlong, jbyteArray, jlongArray, jintArray);

/*
 * Class:     uk_ac_manchester_tornado_drivers_spirv_ocl_SPIRVOCLNativeDispatcher
 * Method:    clBuildProgram_native
 * Signature: (JI[JLjava/lang/String;)I
 */
JNIEXPORT jint JNICALL Java_uk_ac_manchester_tornado_drivers_spirv_ocl_SPIRVOCLNativeDispatcher_clBuildProgram_1native
        (JNIEnv *, jobject, jlong, jint, jlongArray, jstring);

/*
 * Class:     uk_ac_manchester_tornado_drivers_spirv_ocl_SPIRVOCLNativeDispatcher
 * Method:    clCreateKernel_native
 * Signature: (JLjava/lang/String;[I)J
 */
JNIEXPORT jlong JNICALL Java_uk_ac_manchester_tornado_drivers_spirv_ocl_SPIRVOCLNativeDispatcher_clCreateKernel_1native
        (JNIEnv *, jobject, jlong, jstring, jintArray);

/*
 * Class:     uk_ac_manchester_tornado_drivers_spirv_ocl_SPIRVOCLNativeDispatcher
 * Method:    clGetProgramBuildInfo_native
 * Signature: (JJ)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_uk_ac_manchester_tornado_drivers_spirv_ocl_SPIRVOCLNativeDispatcher_clGetProgramBuildInfo_1native
        (JNIEnv *, jobject, jlong, jlong);

/*
 * Class:     uk_ac_manchester_tornado_drivers_spirv_ocl_SPIRVOCLNativeDispatcher
 * Method:    clSetKernelArg_native
 * Signature: (JIIJ)I
 */
JNIEXPORT jint JNICALL Java_uk_ac_manchester_tornado_drivers_spirv_ocl_SPIRVOCLNativeDispatcher_clSetKernelArg_1native
        (JNIEnv *, jobject, jlong, jint, jint, jlong);

/*
 * Class:     uk_ac_manchester_tornado_drivers_spirv_ocl_SPIRVOCLNativeDispatcher
 * Method:    clEnqueueNDRangeKernel_native
 * Signature: (JJI[J[J[J[J[J)I
 */
JNIEXPORT jint JNICALL Java_uk_ac_manchester_tornado_drivers_spirv_ocl_SPIRVOCLNativeDispatcher_clEnqueueNDRangeKernel_1native
        (JNIEnv *, jobject, jlong, jlong, jint, jlongArray, jlongArray, jlongArray, jlongArray, jlongArray);

#ifdef __cplusplus
}
#endif
#endif
