/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class uk_ac_manchester_tornado_drivers_spirv_ocl_SPIRVOCLNativeCompiler */

#ifndef _Included_uk_ac_manchester_tornado_drivers_spirv_ocl_SPIRVOCLNativeCompiler
#define _Included_uk_ac_manchester_tornado_drivers_spirv_ocl_SPIRVOCLNativeCompiler
#ifdef __cplusplus
extern "C" {
#endif
#undef uk_ac_manchester_tornado_drivers_spirv_ocl_SPIRVOCLNativeCompiler_CL_SUCCESS
#define uk_ac_manchester_tornado_drivers_spirv_ocl_SPIRVOCLNativeCompiler_CL_SUCCESS 0L
/*
 * Class:     uk_ac_manchester_tornado_drivers_spirv_ocl_SPIRVOCLNativeCompiler
 * Method:    clCreateProgramWithIL_native
 * Signature: (J[B[J[I)J
 */
JNIEXPORT jlong JNICALL Java_uk_ac_manchester_tornado_drivers_spirv_ocl_SPIRVOCLNativeCompiler_clCreateProgramWithIL_1native
        (JNIEnv *, jobject, jlong, jbyteArray, jlongArray, jintArray);

/*
 * Class:     uk_ac_manchester_tornado_drivers_spirv_ocl_SPIRVOCLNativeCompiler
 * Method:    clBuildProgram_native
 * Signature: (JI[JLjava/lang/String;)I
 */
JNIEXPORT jint JNICALL Java_uk_ac_manchester_tornado_drivers_spirv_ocl_SPIRVOCLNativeCompiler_clBuildProgram_1native
        (JNIEnv *, jobject, jlong, jint, jlongArray, jstring);

/*
 * Class:     uk_ac_manchester_tornado_drivers_spirv_ocl_SPIRVOCLNativeCompiler
 * Method:    clCreateKernel_native
 * Signature: (JLjava/lang/String;[I)J
 */
JNIEXPORT jlong JNICALL Java_uk_ac_manchester_tornado_drivers_spirv_ocl_SPIRVOCLNativeCompiler_clCreateKernel_1native
        (JNIEnv *, jobject, jlong, jstring, jintArray);

#ifdef __cplusplus
}
#endif
#endif