/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class uk_ac_manchester_tornado_drivers_spirv_ocl_SPIRVOCLNativeCompiler */

#ifndef _Included_uk_ac_manchester_tornado_drivers_spirv_ocl_SPIRVOCLNativeCompiler
#define _Included_uk_ac_manchester_tornado_drivers_spirv_ocl_SPIRVOCLNativeCompiler
#ifdef __cplusplus
extern "C" {
#endif
#undef uk_ac_manchester_tornado_drivers_spirv_ocl_SPIRVOCLNativeCompiler_CL_SUCCESS
#define uk_ac_manchester_tornado_drivers_spirv_ocl_SPIRVOCLNativeCompiler_CL_SUCCESS 0L
/*
 * Class:     uk_ac_manchester_tornado_drivers_spirv_ocl_SPIRVOCLNativeCompiler
 * Method:    clCreateProgramWithIL_native
 * Signature: (J[B[J[I)J
 */
JNIEXPORT jlong JNICALL Java_uk_ac_manchester_tornado_drivers_spirv_ocl_SPIRVOCLNativeCompiler_clCreateProgramWithIL_1native
        (JNIEnv *, jobject, jlong, jbyteArray, jlongArray, jintArray);

/*
 * Class:     uk_ac_manchester_tornado_drivers_spirv_ocl_SPIRVOCLNativeCompiler
 * Method:    clBuildProgram_native
 * Signature: (JI[JLjava/lang/String;)I
 */
JNIEXPORT jint JNICALL Java_uk_ac_manchester_tornado_drivers_spirv_ocl_SPIRVOCLNativeCompiler_clBuildProgram_1native
        (JNIEnv *, jobject, jlong, jint, jlongArray, jstring);

/*
 * Class:     uk_ac_manchester_tornado_drivers_spirv_ocl_SPIRVOCLNativeCompiler
 * Method:    clCreateKernel_native
 * Signature: (JLjava/lang/String;[I)J
 */
JNIEXPORT jlong JNICALL Java_uk_ac_manchester_tornado_drivers_spirv_ocl_SPIRVOCLNativeCompiler_clCreateKernel_1native
        (JNIEnv *, jobject, jlong, jstring, jintArray);

/*
 * Class:     uk_ac_manchester_tornado_drivers_spirv_ocl_SPIRVOCLNativeCompiler
 * Method:    clGetProgramBuildInfo_native
 * Signature: (JJ)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_uk_ac_manchester_tornado_drivers_spirv_ocl_SPIRVOCLNativeCompiler_clGetProgramBuildInfo_1native
        (JNIEnv *, jobject, jlong, jlong);

/*
 * Class:     uk_ac_manchester_tornado_drivers_spirv_ocl_SPIRVOCLNativeCompiler
 * Method:    clSetKernelArg_native
 * Signature: (JIIJ)I
 */
JNIEXPORT jint JNICALL Java_uk_ac_manchester_tornado_drivers_spirv_ocl_SPIRVOCLNativeCompiler_clSetKernelArg_1native
        (JNIEnv *, jobject, jlong, jint, jint, jlong);

/*
 * Class:     uk_ac_manchester_tornado_drivers_spirv_ocl_SPIRVOCLNativeCompiler
 * Method:    clEnqueueNDRangeKernel_native
 * Signature: (JJI[J[J[JLjava/lang/Object;Ljava/lang/Object;)I
 */
JNIEXPORT jint JNICALL Java_uk_ac_manchester_tornado_drivers_spirv_ocl_SPIRVOCLNativeCompiler_clEnqueueNDRangeKernel_1native
        (JNIEnv *, jobject, jlong, jlong, jint, jlongArray, jlongArray, jlongArray, jobject, jobject);

#ifdef __cplusplus
}
#endif
#endif