/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class uk_ac_manchester_tornado_drivers_cuda_CUDAStream */

#ifndef _Included_uk_ac_manchester_tornado_drivers_cuda_CUDAStream
#define _Included_uk_ac_manchester_tornado_drivers_cuda_CUDAStream
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     uk_ac_manchester_tornado_drivers_cuda_CUDAStream
 * Method:    writeArrayDtoH
 * Signature: (JJ[BJ[B)[B
 */
JNIEXPORT jobjectArray JNICALL Java_uk_ac_manchester_tornado_drivers_cuda_CUDAStream_writeArrayDtoH__JJ_3BJ_3B
  (JNIEnv *, jclass, jlong, jlong, jbyteArray, jlong, jbyteArray);

/*
 * Class:     uk_ac_manchester_tornado_drivers_cuda_CUDAStream
 * Method:    writeArrayDtoH
 * Signature: (JJ[SJ[B)[B
 */
JNIEXPORT jobjectArray JNICALL Java_uk_ac_manchester_tornado_drivers_cuda_CUDAStream_writeArrayDtoH__JJ_3SJ_3B
  (JNIEnv *, jclass, jlong, jlong, jshortArray, jlong, jbyteArray);

/*
 * Class:     uk_ac_manchester_tornado_drivers_cuda_CUDAStream
 * Method:    writeArrayDtoH
 * Signature: (JJ[CJ[B)[B
 */
JNIEXPORT jobjectArray JNICALL Java_uk_ac_manchester_tornado_drivers_cuda_CUDAStream_writeArrayDtoH__JJ_3CJ_3B
  (JNIEnv *, jclass, jlong, jlong, jcharArray, jlong, jbyteArray);

/*
 * Class:     uk_ac_manchester_tornado_drivers_cuda_CUDAStream
 * Method:    writeArrayDtoH
 * Signature: (JJ[IJ[B)[B
 */
JNIEXPORT jobjectArray JNICALL Java_uk_ac_manchester_tornado_drivers_cuda_CUDAStream_writeArrayDtoH__JJ_3IJ_3B
  (JNIEnv *, jclass, jlong, jlong, jintArray, jlong, jbyteArray);

/*
 * Class:     uk_ac_manchester_tornado_drivers_cuda_CUDAStream
 * Method:    writeArrayDtoH
 * Signature: (JJ[JJ[B)[B
 */
JNIEXPORT jobjectArray JNICALL Java_uk_ac_manchester_tornado_drivers_cuda_CUDAStream_writeArrayDtoH__JJ_3JJ_3B
  (JNIEnv *, jclass, jlong, jlong, jlongArray, jlong, jbyteArray);

/*
 * Class:     uk_ac_manchester_tornado_drivers_cuda_CUDAStream
 * Method:    writeArrayDtoH
 * Signature: (JJ[FJ[B)[B
 */
JNIEXPORT jobjectArray JNICALL Java_uk_ac_manchester_tornado_drivers_cuda_CUDAStream_writeArrayDtoH__JJ_3FJ_3B
  (JNIEnv *, jclass, jlong, jlong, jfloatArray, jlong, jbyteArray);

/*
 * Class:     uk_ac_manchester_tornado_drivers_cuda_CUDAStream
 * Method:    writeArrayDtoH
 * Signature: (JJ[DJ[B)[B
 */
JNIEXPORT jobjectArray JNICALL Java_uk_ac_manchester_tornado_drivers_cuda_CUDAStream_writeArrayDtoH__JJ_3DJ_3B
  (JNIEnv *, jclass, jlong, jlong, jdoubleArray, jlong, jbyteArray);

/*
 * Class:     uk_ac_manchester_tornado_drivers_cuda_CUDAStream
 * Method:    writeArrayDtoHAsync
 * Signature: (JJ[BJ[B)I
 */
JNIEXPORT jobjectArray JNICALL Java_uk_ac_manchester_tornado_drivers_cuda_CUDAStream_writeArrayDtoHAsync__JJ_3BJ_3B
  (JNIEnv *, jclass, jlong, jlong, jbyteArray, jlong, jbyteArray);

/*
 * Class:     uk_ac_manchester_tornado_drivers_cuda_CUDAStream
 * Method:    writeArrayDtoHAsync
 * Signature: (JJ[SJ[B)I
 */
JNIEXPORT jobjectArray JNICALL Java_uk_ac_manchester_tornado_drivers_cuda_CUDAStream_writeArrayDtoHAsync__JJ_3SJ_3B
  (JNIEnv *, jclass, jlong, jlong, jshortArray, jlong, jbyteArray);

/*
 * Class:     uk_ac_manchester_tornado_drivers_cuda_CUDAStream
 * Method:    writeArrayDtoHAsync
 * Signature: (JJ[CJ[B)I
 */
JNIEXPORT jobjectArray JNICALL Java_uk_ac_manchester_tornado_drivers_cuda_CUDAStream_writeArrayDtoHAsync__JJ_3CJ_3B
  (JNIEnv *, jclass, jlong, jlong, jcharArray, jlong, jbyteArray);

/*
 * Class:     uk_ac_manchester_tornado_drivers_cuda_CUDAStream
 * Method:    writeArrayDtoHAsync
 * Signature: (JJ[IJ[B)I
 */
JNIEXPORT jobjectArray JNICALL Java_uk_ac_manchester_tornado_drivers_cuda_CUDAStream_writeArrayDtoHAsync__JJ_3IJ_3B
  (JNIEnv *, jclass, jlong, jlong, jintArray, jlong, jbyteArray);

/*
 * Class:     uk_ac_manchester_tornado_drivers_cuda_CUDAStream
 * Method:    writeArrayDtoHAsync
 * Signature: (JJ[JJ[B)I
 */
JNIEXPORT jobjectArray JNICALL Java_uk_ac_manchester_tornado_drivers_cuda_CUDAStream_writeArrayDtoHAsync__JJ_3JJ_3B
  (JNIEnv *, jclass, jlong, jlong, jlongArray, jlong, jbyteArray);

/*
 * Class:     uk_ac_manchester_tornado_drivers_cuda_CUDAStream
 * Method:    writeArrayDtoHAsync
 * Signature: (JJ[FJ[B)I
 */
JNIEXPORT jobjectArray JNICALL Java_uk_ac_manchester_tornado_drivers_cuda_CUDAStream_writeArrayDtoHAsync__JJ_3FJ_3B
  (JNIEnv *, jclass, jlong, jlong, jfloatArray, jlong, jbyteArray);

/*
 * Class:     uk_ac_manchester_tornado_drivers_cuda_CUDAStream
 * Method:    writeArrayDtoHAsync
 * Signature: (JJ[DJ[B)I
 */
JNIEXPORT jobjectArray JNICALL Java_uk_ac_manchester_tornado_drivers_cuda_CUDAStream_writeArrayDtoHAsync__JJ_3DJ_3B
  (JNIEnv *, jclass, jlong, jlong, jdoubleArray, jlong, jbyteArray);

/*
 * Class:     uk_ac_manchester_tornado_drivers_cuda_CUDAStream
 * Method:    writeArrayHtoD
 * Signature: (JJ[BJ[B)V
 */
JNIEXPORT jobjectArray JNICALL Java_uk_ac_manchester_tornado_drivers_cuda_CUDAStream_writeArrayHtoD__JJ_3BJ_3B
  (JNIEnv *, jclass, jlong, jlong, jbyteArray, jlong, jbyteArray);

/*
 * Class:     uk_ac_manchester_tornado_drivers_cuda_CUDAStream
 * Method:    writeArrayHtoD
 * Signature: (JJ[SJ[B)V
 */
JNIEXPORT jobjectArray JNICALL Java_uk_ac_manchester_tornado_drivers_cuda_CUDAStream_writeArrayHtoD__JJ_3SJ_3B
  (JNIEnv *, jclass, jlong, jlong, jshortArray, jlong, jbyteArray);

/*
 * Class:     uk_ac_manchester_tornado_drivers_cuda_CUDAStream
 * Method:    writeArrayHtoD
 * Signature: (JJ[CJ[B)V
 */
JNIEXPORT jobjectArray JNICALL Java_uk_ac_manchester_tornado_drivers_cuda_CUDAStream_writeArrayHtoD__JJ_3CJ_3B
  (JNIEnv *, jclass, jlong, jlong, jcharArray, jlong, jbyteArray);

/*
 * Class:     uk_ac_manchester_tornado_drivers_cuda_CUDAStream
 * Method:    writeArrayHtoD
 * Signature: (JJ[IJ[B)V
 */
JNIEXPORT jobjectArray JNICALL Java_uk_ac_manchester_tornado_drivers_cuda_CUDAStream_writeArrayHtoD__JJ_3IJ_3B
  (JNIEnv *, jclass, jlong, jlong, jintArray, jlong, jbyteArray);

/*
 * Class:     uk_ac_manchester_tornado_drivers_cuda_CUDAStream
 * Method:    writeArrayHtoD
 * Signature: (JJ[JJ[B)V
 */
JNIEXPORT jobjectArray JNICALL Java_uk_ac_manchester_tornado_drivers_cuda_CUDAStream_writeArrayHtoD__JJ_3JJ_3B
  (JNIEnv *, jclass, jlong, jlong, jlongArray, jlong, jbyteArray);

/*
 * Class:     uk_ac_manchester_tornado_drivers_cuda_CUDAStream
 * Method:    writeArrayHtoD
 * Signature: (JJ[FJ[B)V
 */
JNIEXPORT jobjectArray JNICALL Java_uk_ac_manchester_tornado_drivers_cuda_CUDAStream_writeArrayHtoD__JJ_3FJ_3B
  (JNIEnv *, jclass, jlong, jlong, jfloatArray, jlong, jbyteArray);

/*
 * Class:     uk_ac_manchester_tornado_drivers_cuda_CUDAStream
 * Method:    writeArrayHtoD
 * Signature: (JJ[DJ[B)V
 */
JNIEXPORT jobjectArray JNICALL Java_uk_ac_manchester_tornado_drivers_cuda_CUDAStream_writeArrayHtoD__JJ_3DJ_3B
  (JNIEnv *, jclass, jlong, jlong, jdoubleArray, jlong, jbyteArray);

/*
 * Class:     uk_ac_manchester_tornado_drivers_cuda_CUDAStream
 * Method:    writeArrayHtoDAsync
 * Signature: (JJ[BJ[B)[B
 */
JNIEXPORT jobjectArray JNICALL Java_uk_ac_manchester_tornado_drivers_cuda_CUDAStream_writeArrayHtoDAsync__JJ_3BJ_3B
  (JNIEnv *, jclass, jlong, jlong, jbyteArray, jlong, jbyteArray);

/*
 * Class:     uk_ac_manchester_tornado_drivers_cuda_CUDAStream
 * Method:    writeArrayHtoDAsync
 * Signature: (JJ[SJ[B)[B
 */
JNIEXPORT jobjectArray JNICALL Java_uk_ac_manchester_tornado_drivers_cuda_CUDAStream_writeArrayHtoDAsync__JJ_3SJ_3B
  (JNIEnv *, jclass, jlong, jlong, jshortArray, jlong, jbyteArray);

/*
 * Class:     uk_ac_manchester_tornado_drivers_cuda_CUDAStream
 * Method:    writeArrayHtoDAsync
 * Signature: (JJ[CJ[B)[B
 */
JNIEXPORT jobjectArray JNICALL Java_uk_ac_manchester_tornado_drivers_cuda_CUDAStream_writeArrayHtoDAsync__JJ_3CJ_3B
  (JNIEnv *, jclass, jlong, jlong, jcharArray, jlong, jbyteArray);

/*
 * Class:     uk_ac_manchester_tornado_drivers_cuda_CUDAStream
 * Method:    writeArrayHtoDAsync
 * Signature: (JJ[IJ[B)[B
 */
JNIEXPORT jobjectArray JNICALL Java_uk_ac_manchester_tornado_drivers_cuda_CUDAStream_writeArrayHtoDAsync__JJ_3IJ_3B
  (JNIEnv *, jclass, jlong, jlong, jintArray, jlong, jbyteArray);

/*
 * Class:     uk_ac_manchester_tornado_drivers_cuda_CUDAStream
 * Method:    writeArrayHtoDAsync
 * Signature: (JJ[JJ[B)[B
 */
JNIEXPORT jobjectArray JNICALL Java_uk_ac_manchester_tornado_drivers_cuda_CUDAStream_writeArrayHtoDAsync__JJ_3JJ_3B
  (JNIEnv *, jclass, jlong, jlong, jlongArray, jlong, jbyteArray);

/*
 * Class:     uk_ac_manchester_tornado_drivers_cuda_CUDAStream
 * Method:    writeArrayHtoDAsync
 * Signature: (JJ[FJ[B)[B
 */
JNIEXPORT jobjectArray JNICALL Java_uk_ac_manchester_tornado_drivers_cuda_CUDAStream_writeArrayHtoDAsync__JJ_3FJ_3B
  (JNIEnv *, jclass, jlong, jlong, jfloatArray, jlong, jbyteArray);

/*
 * Class:     uk_ac_manchester_tornado_drivers_cuda_CUDAStream
 * Method:    writeArrayHtoDAsync
 * Signature: (JJ[DJ[B)[B
 */
JNIEXPORT jobjectArray JNICALL Java_uk_ac_manchester_tornado_drivers_cuda_CUDAStream_writeArrayHtoDAsync__JJ_3DJ_3B
  (JNIEnv *, jclass, jlong, jlong, jdoubleArray, jlong, jbyteArray);

/*
 * Class:     uk_ac_manchester_tornado_drivers_cuda_CUDAStream
 * Method:    cuLaunchKernel
 * Signature: ([BLjava/lang/String;IIIIIIJ[B[B)[B
 */
JNIEXPORT jobjectArray JNICALL Java_uk_ac_manchester_tornado_drivers_cuda_CUDAStream_cuLaunchKernel
  (JNIEnv *, jclass, jbyteArray, jstring, jint, jint, jint, jint, jint, jint, jlong, jbyteArray, jbyteArray);

/*
 * Class:     uk_ac_manchester_tornado_drivers_cuda_CUDAStream
 * Method:    cuCreateStream
 * Signature: ()[B
 */
JNIEXPORT jbyteArray JNICALL Java_uk_ac_manchester_tornado_drivers_cuda_CUDAStream_cuCreateStream
  (JNIEnv *, jclass);

/*
 * Class:     uk_ac_manchester_tornado_drivers_cuda_CUDAStream
 * Method:    cuDestroyStream
 * Signature: ([B)V
 */
JNIEXPORT void JNICALL Java_uk_ac_manchester_tornado_drivers_cuda_CUDAStream_cuDestroyStream
  (JNIEnv *, jclass, jbyteArray);

/*
 * Class:     uk_ac_manchester_tornado_drivers_cuda_CUDAStream
 * Method:    cuStreamSynchronize
 * Signature: ([B)V
 */
JNIEXPORT void JNICALL Java_uk_ac_manchester_tornado_drivers_cuda_CUDAStream_cuStreamSynchronize
  (JNIEnv *, jclass, jbyteArray);

/*
 * Class:     uk_ac_manchester_tornado_drivers_cuda_CUDAStream
 * Method:    cuEventCreateAndRecord
 * Signature: (Z[B)[B
 */
JNIEXPORT jbyteArray JNICALL Java_uk_ac_manchester_tornado_drivers_cuda_CUDAStream_cuEventCreateAndRecord
  (JNIEnv *, jclass, jboolean, jbyteArray);

#ifdef __cplusplus
}
#endif
#endif
