/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class uk_ac_manchester_tornado_drivers_cuda_CUDAEvent */

#ifndef _Included_uk_ac_manchester_tornado_drivers_cuda_CUDAEvent
#define _Included_uk_ac_manchester_tornado_drivers_cuda_CUDAEvent
#ifdef __cplusplus
extern "C" {
#endif


jbyteArray array_from_event(JNIEnv *env, CUevent *event);

/*
 * Class:     uk_ac_manchester_tornado_drivers_cuda_CUDAEvent
 * Method:    cuEventDestroy
 * Signature: ([B)V
 */
JNIEXPORT void JNICALL Java_uk_ac_manchester_tornado_drivers_cuda_CUDAEvent_cuEventDestroy
  (JNIEnv *, jclass, jbyteArray);

#ifdef __cplusplus
}
#endif
#endif
