/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class uk_ac_manchester_tornado_drivers_cuda_CUDAStream */

#ifndef _Included_uk_ac_manchester_tornado_drivers_cuda_CUDAStream
#define _Included_uk_ac_manchester_tornado_drivers_cuda_CUDAStream
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     uk_ac_manchester_tornado_drivers_cuda_CUDAStream
 * Method:    writeArrayHtoDAsync
 * Signature: (JJJ[BJ[I)I
 */
JNIEXPORT jint JNICALL Java_uk_ac_manchester_tornado_drivers_cuda_CUDAStream_writeArrayHtoDAsync__JJJ_3BJ_3I
  (JNIEnv *, jclass, jlong, jlong, jlong, jbyteArray, jlong, jintArray);

/*
 * Class:     uk_ac_manchester_tornado_drivers_cuda_CUDAStream
 * Method:    writeArrayHtoDAsync
 * Signature: (JJJ[IJ[I)I
 */
JNIEXPORT jint JNICALL Java_uk_ac_manchester_tornado_drivers_cuda_CUDAStream_writeArrayHtoDAsync__JJJ_3IJ_3I
  (JNIEnv *, jclass, jlong, jlong, jlong, jintArray, jlong, jintArray);

#ifdef __cplusplus
}
#endif
#endif