/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class uk_ac_manchester_tornado_drivers_cuda_CUDAPlatform */

#ifndef _Included_uk_ac_manchester_tornado_drivers_cuda_CUDAPlatform
#define _Included_uk_ac_manchester_tornado_drivers_cuda_CUDAPlatform
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     uk_ac_manchester_tornado_drivers_cuda_CUDAPlatform
 * Method:    cuDeviceGetCount
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_uk_ac_manchester_tornado_drivers_cuda_CUDAPlatform_cuDeviceGetCount
  (JNIEnv *, jclass);

#ifdef __cplusplus
}
#endif
#endif