/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class uk_ac_manchester_tornado_drivers_cuda_CUDAContext */

#ifndef _Included_uk_ac_manchester_tornado_drivers_cuda_CUDAContext
#define _Included_uk_ac_manchester_tornado_drivers_cuda_CUDAContext
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     uk_ac_manchester_tornado_drivers_cuda_CUDAContext
 * Method:    cuCtxCreate
 * Signature: (I)I
 */
JNIEXPORT void JNICALL Java_uk_ac_manchester_tornado_drivers_cuda_CUDAContext_cuCtxCreate
  (JNIEnv *, jclass, jint);

/*
 * Class:     uk_ac_manchester_tornado_drivers_cuda_CUDAContext
 * Method:    cuCtxDestroy
 * Signature: (I)V
 */
JNIEXPORT void JNICALL Java_uk_ac_manchester_tornado_drivers_cuda_CUDAContext_cuCtxDestroy
  (JNIEnv *, jclass, jint);

#ifdef __cplusplus
}
#endif
#endif
