/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class uk_ac_manchester_tornado_drivers_ptx_PTXEvent */

#ifndef _Included_uk_ac_manchester_tornado_drivers_ptx_PTXEvent
#define _Included_uk_ac_manchester_tornado_drivers_ptx_PTXEvent


jbyteArray array_from_event(JNIEnv *env, CUevent *event);

jobjectArray wrapper_from_events(JNIEnv *env, CUevent *event1, CUevent *event2);

/*
 * Class:     uk_ac_manchester_tornado_drivers_ptx_PTXEvent
 * Method:    cuEventDestroy
 * Signature: ([B)J
 */
JNIEXPORT jlong JNICALL Java_uk_ac_manchester_tornado_drivers_ptx_PTXEvent_cuEventDestroy
  (JNIEnv *, jclass, jbyteArray);

/*
 * Class:     uk_ac_manchester_tornado_drivers_ptx_PTXEvent
 * Method:    cuEventSynchronize
 * Signature: ([[B)V
 */
JNIEXPORT void JNICALL Java_uk_ac_manchester_tornado_drivers_ptx_PTXEvent_cuEventSynchronize
  (JNIEnv *, jclass, jobjectArray);

 /*
  * Class:     uk_ac_manchester_tornado_drivers_ptx_PTXEvent
  * Method:    cuEventElapsedTime
  * Signature: ([B)V
  */
JNIEXPORT jlong JNICALL Java_uk_ac_manchester_tornado_drivers_ptx_PTXEvent_cuEventElapsedTime
 (JNIEnv *env, jclass clazz, jobjectArray wrapper);

/*
 * Class:     uk_ac_manchester_tornado_drivers_ptx_PTXEvent
 * Method:    cuEventQuery
 * Signature: ([B)V
 */
JNIEXPORT jboolean JNICALL Java_uk_ac_manchester_tornado_drivers_ptx_PTXEvent_cuEventQuery
  (JNIEnv *, jclass, jbyteArray);

#endif
