/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class uk_ac_manchester_tornado_drivers_ptx_PTXPlatform */

#ifndef _Included_uk_ac_manchester_tornado_drivers_ptx_PTXPlatform
#define _Included_uk_ac_manchester_tornado_drivers_ptx_PTXPlatform
/*
 * Class:     uk_ac_manchester_tornado_drivers_ptx_PTXPlatform
 * Method:    cuDeviceGetCount
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_uk_ac_manchester_tornado_drivers_ptx_PTXPlatform_cuDeviceGetCount
  (JNIEnv *, jclass);

#endif