/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class jacc_runtime_drivers_opencl_OCLDevice */

#ifndef _Included_tornado_drivers_opencl_OCLDevice
#define _Included_tornado_drivers_opencl_OCLDevice
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     jacc_runtime_drivers_opencl_OCLDevice
 * Method:    clGetDeviceInfo
 * Signature: (JI[B)V
 */
JNIEXPORT void JNICALL Java_tornado_drivers_opencl_OCLDevice_clGetDeviceInfo
  (JNIEnv *, jclass, jlong, jint, jbyteArray);

#ifdef __cplusplus
}
#endif
#endif
