/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class tornado_drivers_opencl_OCLKernel */

#ifndef _Included_tornado_drivers_opencl_OCLKernel
#define _Included_tornado_drivers_opencl_OCLKernel
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     tornado_drivers_opencl_OCLKernel
 * Method:    clReleaseKernel
 * Signature: (J)V
 */
JNIEXPORT void JNICALL Java_tornado_drivers_opencl_OCLKernel_clReleaseKernel
  (JNIEnv *, jclass, jlong);

/*
 * Class:     tornado_drivers_opencl_OCLKernel
 * Method:    clSetKernelArg
 * Signature: (JIJ[B)V
 */
JNIEXPORT void JNICALL Java_tornado_drivers_opencl_OCLKernel_clSetKernelArg
  (JNIEnv *, jclass, jlong, jint, jlong, jbyteArray);

/*
 * Class:     tornado_drivers_opencl_OCLKernel
 * Method:    clGetKernelInfo
 * Signature: (JI[B)V
 */
JNIEXPORT void JNICALL Java_tornado_drivers_opencl_OCLKernel_clGetKernelInfo
  (JNIEnv *, jclass, jlong, jint, jbyteArray);

#ifdef __cplusplus
}
#endif
#endif
