/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class tornado_drivers_opencl_OCLProgram */

#ifndef _Included_tornado_drivers_opencl_OCLProgram
#define _Included_tornado_drivers_opencl_OCLProgram
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     tornado_drivers_opencl_OCLProgram
 * Method:    clReleaseProgram
 * Signature: (J)V
 */
JNIEXPORT void JNICALL Java_tornado_drivers_opencl_OCLProgram_clReleaseProgram
  (JNIEnv *, jclass, jlong);

/*
 * Class:     tornado_drivers_opencl_OCLProgram
 * Method:    clBuildProgram
 * Signature: (J[JLjava/lang/String;)V
 */
JNIEXPORT void JNICALL Java_tornado_drivers_opencl_OCLProgram_clBuildProgram
  (JNIEnv *, jclass, jlong, jlongArray, jstring);

/*
 * Class:     tornado_drivers_opencl_OCLProgram
 * Method:    clGetProgramInfo
 * Signature: (JI[B)V
 */
JNIEXPORT void JNICALL Java_tornado_drivers_opencl_OCLProgram_clGetProgramInfo
  (JNIEnv *, jclass, jlong, jint, jbyteArray);

/*
 * Class:     tornado_drivers_opencl_OCLProgram
 * Method:    clGetProgramBuildInfo
 * Signature: (JJI[B)V
 */
JNIEXPORT void JNICALL Java_tornado_drivers_opencl_OCLProgram_clGetProgramBuildInfo
  (JNIEnv *, jclass, jlong, jlong, jint, jbyteArray);

/*
 * Class:     tornado_drivers_opencl_OCLProgram
 * Method:    clCreateKernel
 * Signature: (JLjava/lang/String;)J
 */
JNIEXPORT jlong JNICALL Java_tornado_drivers_opencl_OCLProgram_clCreateKernel
  (JNIEnv *, jclass, jlong, jstring);

/*
 * Class:     tornado_drivers_opencl_OCLProgram
 * Method:    getBinaries
 * Signature: (JJ[B)V
 */
JNIEXPORT void JNICALL Java_tornado_drivers_opencl_OCLProgram_getBinaries
  (JNIEnv *, jclass, jlong, jlong, jbyteArray);

#ifdef __cplusplus
}
#endif
#endif
