/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class jacc_runtime_drivers_opencl_OCLPlatform */

#ifndef _Included_tornado_drivers_opencl_OCLPlatform
#define _Included_tornado_drivers_opencl_OCLPlatform
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     jacc_runtime_drivers_opencl_OCLPlatform
 * Method:    clGetPlatformInfo
 * Signature: (JI)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_tornado_drivers_opencl_OCLPlatform_clGetPlatformInfo
  (JNIEnv *, jclass, jlong, jint);

/*
 * Class:     jacc_runtime_drivers_opencl_OCLPlatform
 * Method:    clGetDeviceCount
 * Signature: (JJ)I
 */
JNIEXPORT jint JNICALL Java_tornado_drivers_opencl_OCLPlatform_clGetDeviceCount
  (JNIEnv *, jclass, jlong, jlong);

/*
 * Class:     jacc_runtime_drivers_opencl_OCLPlatform
 * Method:    clGetDeviceIDs
 * Signature: (JJ[J)I
 */
JNIEXPORT jint JNICALL Java_tornado_drivers_opencl_OCLPlatform_clGetDeviceIDs
  (JNIEnv *, jclass, jlong, jlong, jlongArray);

/*
 * Class:     jacc_runtime_drivers_opencl_OCLPlatform
 * Method:    clCreateContext
 * Signature: (J[J)J
 */
JNIEXPORT jlong JNICALL Java_tornado_drivers_opencl_OCLPlatform_clCreateContext
  (JNIEnv *, jclass, jlong, jlongArray);

#ifdef __cplusplus
}
#endif
#endif
