/*
 * Copyright (c) 2024, APT Group, Department of Computer Science,
 * The University of Manchester.
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 * http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 *
 */
package uk.ac.manchester.tornado.fuzz.report;

import uk.ac.manchester.tornado.api.types.arrays.DoubleArray;
import uk.ac.manchester.tornado.api.types.arrays.FloatArray;
import uk.ac.manchester.tornado.api.types.arrays.IntArray;
import uk.ac.manchester.tornado.api.types.arrays.LongArray;
import uk.ac.manchester.tornado.fuzz.ElemType;
import uk.ac.manchester.tornado.fuzz.ReproSpec;

/**
 * Renders a {@link ReproSpec} into a standalone JUnit4 test that extends
 * {@code TornadoTestBase}, embeds the exact failing inputs and the golden
 * expected output as literals (float/double via bit patterns for exactness), and
 * fails on the CUDA backend the same way the fuzzer observed. Drop the file into
 * {@code tornado-unittests/.../fuzz/} and it becomes a permanent regression test.
 */
public final class JUnitEmitter {

    public static final String PACKAGE = "uk.ac.manchester.tornado.unittests.fuzz";

    private JUnitEmitter() {
    }

    public static String emit(ReproSpec spec, String className) {
        StringBuilder sb = new StringBuilder();
        sb.append("package ").append(PACKAGE).append(";\n\n");
        sb.append("import static org.junit.Assert.assertEquals;\n\n");
        sb.append("import org.junit.Test;\n\n");
        sb.append("import uk.ac.manchester.tornado.api.GridScheduler;\n");
        sb.append("import uk.ac.manchester.tornado.api.KernelContext;\n");
        sb.append("import uk.ac.manchester.tornado.api.TaskGraph;\n");
        sb.append("import uk.ac.manchester.tornado.api.TornadoExecutionPlan;\n");
        sb.append("import uk.ac.manchester.tornado.api.WorkerGrid;\n");
        sb.append("import uk.ac.manchester.tornado.api.WorkerGrid1D;\n");
        sb.append("import uk.ac.manchester.tornado.api.enums.DataTransferMode;\n");
        sb.append("import uk.ac.manchester.tornado.api.math.TornadoMath;\n");
        sb.append("import uk.ac.manchester.tornado.api.types.arrays.DoubleArray;\n");
        sb.append("import uk.ac.manchester.tornado.api.types.arrays.FloatArray;\n");
        sb.append("import uk.ac.manchester.tornado.api.types.arrays.IntArray;\n");
        sb.append("import uk.ac.manchester.tornado.api.types.arrays.LongArray;\n");
        sb.append("import uk.ac.manchester.tornado.unittests.common.TornadoTestBase;\n\n");

        sb.append("/**\n");
        sb.append(" * Auto-generated by tornado-fuzz. Reproduce on the CUDA backend with:\n");
        sb.append(" *   tornado-test -V ").append(PACKAGE).append('.').append(className).append("#test \\\n");
        sb.append(" *       --jvm=\"-Dtornado.cuda.priority=100\"\n");
        sb.append(" */\n");
        sb.append("public class ").append(className).append(" extends TornadoTestBase {\n\n");

        // The kernel method (named `fuzzedKernel`; `kernel` is a reserved CUDA/OpenCL token).
        for (String line : spec.kernelSource.split("\n")) {
            sb.append("    ").append(line).append('\n');
        }
        sb.append('\n');

        sb.append("    @Test\n");
        sb.append("    public void test() throws Exception {\n");

        // Rebuild inputs from literals.
        for (ReproSpec.Binding b : spec.bindings) {
            if (b.output) {
                sb.append(allocateZeroed(b.name, b.type, size(b.array)));
            } else {
                sb.append(literal(b.name, b.type, b.array));
            }
        }
        if (spec.scalarArgName != null) {
            sb.append("        final int ").append(spec.scalarArgName).append(" = ").append(spec.scalarArgValue).append(";\n");
        }

        sb.append("        KernelContext context = new KernelContext();\n");
        sb.append("        WorkerGrid worker = new WorkerGrid1D(").append(spec.globalWork).append(");\n");
        sb.append("        worker.setGlobalWork(").append(spec.globalWork).append(", 1, 1);\n");
        sb.append("        worker.setLocalWork(").append(spec.localWork).append(", 1, 1);\n");
        sb.append("        GridScheduler gridScheduler = new GridScheduler();\n");
        sb.append("        gridScheduler.addWorkerGrid(\"fuzz.t0\", worker);\n");

        // transferToDevice list: every copy-in binding.
        StringBuilder copyIn = new StringBuilder();
        for (ReproSpec.Binding b : spec.bindings) {
            if (b.copyIn) {
                copyIn.append(", ").append(b.name);
            }
        }
        StringBuilder taskArgs = new StringBuilder("context");
        for (ReproSpec.Binding b : spec.bindings) {
            taskArgs.append(", ").append(b.name);
        }
        if (spec.scalarArgName != null) {
            taskArgs.append(", ").append(spec.scalarArgName);
        }

        sb.append("        TaskGraph taskGraph = new TaskGraph(\"fuzz\")\n");
        sb.append("                .transferToDevice(DataTransferMode.FIRST_EXECUTION").append(copyIn).append(")\n");
        sb.append("                .task(\"t0\", ").append(className).append("::fuzzedKernel, ").append(taskArgs).append(")\n");
        sb.append("                .transferToHost(DataTransferMode.EVERY_EXECUTION, ").append(spec.outputName).append(");\n");
        sb.append("        try (TornadoExecutionPlan plan = new TornadoExecutionPlan(taskGraph.snapshot())) {\n");
        sb.append("            plan.withGridScheduler(gridScheduler).execute();\n");
        sb.append("        }\n\n");

        // Expected literals + assertions.
        sb.append(literal("expected", spec.elemType, spec.expectedOutput));
        sb.append("        for (int i = 0; i < expected.getSize(); i++) {\n");
        switch (spec.elemType) {
            case INT, LONG -> sb.append("            assertEquals(expected.get(i), ").append(spec.outputName).append(".get(i));\n");
            case FLOAT -> sb.append("            assertEquals(expected.get(i), ").append(spec.outputName).append(".get(i), 0.001f);\n");
            case DOUBLE -> sb.append("            assertEquals(expected.get(i), ").append(spec.outputName).append(".get(i), 1e-6);\n");
        }
        sb.append("        }\n");
        sb.append("    }\n");
        sb.append("}\n");
        return sb.toString();
    }

    private static int size(Object array) {
        if (array instanceof IntArray a) {
            return a.getSize();
        }
        if (array instanceof LongArray a) {
            return a.getSize();
        }
        if (array instanceof FloatArray a) {
            return a.getSize();
        }
        if (array instanceof DoubleArray a) {
            return a.getSize();
        }
        throw new IllegalArgumentException("Unsupported array type: " + array.getClass());
    }

    private static String allocateZeroed(String name, ElemType type, int size) {
        return "        " + type.arrayType + " " + name + " = new " + type.arrayType + "(" + size + ");\n";
    }

    private static String literal(String name, ElemType type, Object array) {
        StringBuilder sb = new StringBuilder();
        switch (type) {
            case INT -> {
                IntArray a = (IntArray) array;
                sb.append("        int[] ").append(name).append("_data = {");
                for (int i = 0; i < a.getSize(); i++) {
                    if (i > 0) {
                        sb.append(", ");
                    }
                    sb.append(a.get(i));
                }
                sb.append("};\n");
                sb.append("        IntArray ").append(name).append(" = new IntArray(").append(name).append("_data.length);\n");
                sb.append("        for (int i = 0; i < ").append(name).append("_data.length; i++) { ").append(name).append(".set(i, ").append(name).append("_data[i]); }\n");
            }
            case LONG -> {
                LongArray a = (LongArray) array;
                sb.append("        long[] ").append(name).append("_data = {");
                for (int i = 0; i < a.getSize(); i++) {
                    if (i > 0) {
                        sb.append(", ");
                    }
                    sb.append(a.get(i)).append('L');
                }
                sb.append("};\n");
                sb.append("        LongArray ").append(name).append(" = new LongArray(").append(name).append("_data.length);\n");
                sb.append("        for (int i = 0; i < ").append(name).append("_data.length; i++) { ").append(name).append(".set(i, ").append(name).append("_data[i]); }\n");
            }
            case FLOAT -> {
                FloatArray a = (FloatArray) array;
                sb.append("        int[] ").append(name).append("_bits = {");
                for (int i = 0; i < a.getSize(); i++) {
                    if (i > 0) {
                        sb.append(", ");
                    }
                    sb.append("0x").append(Integer.toHexString(Float.floatToRawIntBits(a.get(i))));
                }
                sb.append("};\n");
                sb.append("        FloatArray ").append(name).append(" = new FloatArray(").append(name).append("_bits.length);\n");
                sb.append("        for (int i = 0; i < ").append(name).append("_bits.length; i++) { ").append(name).append(".set(i, Float.intBitsToFloat(").append(name).append("_bits[i])); }\n");
            }
            case DOUBLE -> {
                DoubleArray a = (DoubleArray) array;
                sb.append("        long[] ").append(name).append("_bits = {");
                for (int i = 0; i < a.getSize(); i++) {
                    if (i > 0) {
                        sb.append(", ");
                    }
                    sb.append("0x").append(Long.toHexString(Double.doubleToRawLongBits(a.get(i)))).append('L');
                }
                sb.append("};\n");
                sb.append("        DoubleArray ").append(name).append(" = new DoubleArray(").append(name).append("_bits.length);\n");
                sb.append("        for (int i = 0; i < ").append(name).append("_bits.length; i++) { ").append(name).append(".set(i, Double.longBitsToDouble(").append(name).append("_bits[i])); }\n");
            }
        }
        return sb.toString();
    }
}
