/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class uk_ac_manchester_tornado_drivers_spirv_levelzero_ZeRelaxedAllocationLimitsExpDescriptor */

#ifndef _Included_uk_ac_manchester_tornado_drivers_spirv_levelzero_MaterializeDescriptors
#define _Included_uk_ac_manchester_tornado_drivers_spirv_levelzero_MaterializeDescriptors
#ifdef __cplusplus
extern "C" {
#endif

/*
 * Class:     uk_ac_manchester_tornado_drivers_spirv_levelzero_ZeDeviceMemAllocDescriptor
 * Method:    materializeNative_ZeDeviceMemAllocDescriptor
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_uk_ac_manchester_tornado_drivers_spirv_levelzero_ZeDeviceMemAllocDescriptor_materializeNative_1ZeDeviceMemAllocDescriptor
        (JNIEnv *, jobject);

/*
 * Class:     uk_ac_manchester_tornado_drivers_spirv_levelzero_ZeFenceDescriptor
 * Method:    materializeNative_ZeFenceDescriptor
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_uk_ac_manchester_tornado_drivers_spirv_levelzero_ZeRelaxedAllocationLimitsExpDescriptor_materializeNative_1ZeFenceDescriptor
        (JNIEnv *, jobject);

/*
 * Class:     uk_ac_manchester_tornado_drivers_spirv_levelzero_ZeRelaxedAllocationLimitsExpDescriptor
 * Method:    materializeNative_ZeRelaxedAllocationLimitsExpDescriptor
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_uk_ac_manchester_tornado_drivers_spirv_levelzero_ZeRelaxedAllocationLimitsExpDescriptor_materializeNative_1ZeRelaxedAllocationLimitsExpDescriptor
        (JNIEnv *, jobject);

/*
 * Class:     uk_ac_manchester_tornado_drivers_spirv_levelzero_ZeEventPoolDescriptor
 * Method:    materializeNative_ZeEventPoolDescriptor
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_uk_ac_manchester_tornado_drivers_spirv_levelzero_ZeRelaxedAllocationLimitsExpDescriptor_materializeNative_1ZeEventPoolDescriptor
        (JNIEnv *, jobject);

/*
 * Class:     uk_ac_manchester_tornado_drivers_spirv_levelzero_ZeCommandListDescriptor
 * Method:    materializeNative_ZeCommandListDescriptor
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_uk_ac_manchester_tornado_drivers_spirv_levelzero_ZeRelaxedAllocationLimitsExpDescriptor_materializeNative_1ZeCommandListDescriptor
        (JNIEnv *, jobject);

/*
 * Class:     uk_ac_manchester_tornado_drivers_spirv_levelzero_ZeHostMemAllocDescriptor
 * Method:    materializeNative_ZeHostMemAllocDescriptor
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_uk_ac_manchester_tornado_drivers_spirv_levelzero_ZeRelaxedAllocationLimitsExpDescriptor_materializeNative_1ZeHostMemAllocDescriptor
        (JNIEnv *, jobject);

/*
 * Class:     uk_ac_manchester_tornado_drivers_spirv_levelzero_ZeKernelDescriptor
 * Method:    materializeNative_ZeKernelDescriptor
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_uk_ac_manchester_tornado_drivers_spirv_levelzero_ZeRelaxedAllocationLimitsExpDescriptor_materializeNative_1ZeKernelDescriptor
        (JNIEnv *, jobject);

/*
 * Class:     uk_ac_manchester_tornado_drivers_spirv_levelzero_ZeCommandQueueDescriptor
 * Method:    materializeNative_ZeCommandQueueDescriptor
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_uk_ac_manchester_tornado_drivers_spirv_levelzero_ZeRelaxedAllocationLimitsExpDescriptor_materializeNative_1ZeCommandQueueDescriptor
        (JNIEnv *, jobject);

/*
 * Class:     uk_ac_manchester_tornado_drivers_spirv_levelzero_ZeModuleDescriptor
 * Method:    materializeNative_ZeModuleDescriptor
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_uk_ac_manchester_tornado_drivers_spirv_levelzero_ZeRelaxedAllocationLimitsExpDescriptor_materializeNative_1ZeModuleDescriptor
        (JNIEnv *, jobject);

/*
 * Class:     uk_ac_manchester_tornado_drivers_spirv_levelzero_ZeEventDescriptor
 * Method:    materializeNative_ZeEventDescriptor
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_uk_ac_manchester_tornado_drivers_spirv_levelzero_ZeRelaxedAllocationLimitsExpDescriptor_materializeNative_1ZeEventDescriptor
        (JNIEnv *, jobject);

/*
 * Class:     uk_ac_manchester_tornado_drivers_spirv_levelzero_ZeContextDescriptor
 * Method:    materializeNative_ZeContextDescriptor
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_uk_ac_manchester_tornado_drivers_spirv_levelzero_ZeRelaxedAllocationLimitsExpDescriptor_materializeNative_1ZeContextDescriptor
        (JNIEnv *, jobject);

#ifdef __cplusplus
}
#endif
#endif
