/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class uk_ac_manchester_tornado_drivers_spirv_levelzero_ZeKernelTimeStampResult */

#ifndef _Included_uk_ac_manchester_tornado_drivers_spirv_levelzero_ZeKernelTimeStampResult
#define _Included_uk_ac_manchester_tornado_drivers_spirv_levelzero_ZeKernelTimeStampResult
#ifdef __cplusplus
extern "C" {
#endif

    /*
     * Class:     uk_ac_manchester_tornado_drivers_spirv_levelzero_ZeKernelTimeStampResult
     * Method:    resolve_native
     * Signature: (Luk/ac/manchester/tornado/drivers/spirv/levelzero/LevelZeroByteBuffer;Luk/ac/manchester/tornado/drivers/spirv/levelzero/ZeKernelTimeStampResult;)I
     */
JNIEXPORT jint JNICALL Java_uk_ac_manchester_tornado_drivers_spirv_levelzero_ZeKernelTimeStampResult_resolve_1native
    (JNIEnv *, jobject, jobject, jobject);

#ifdef __cplusplus
}
#endif
#endif
