/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class uk_ac_manchester_tornado_drivers_spirv_levelzero_LevelZeroDevice */

#ifndef _Included_uk_ac_manchester_tornado_drivers_spirv_levelzero_LevelZeroDevice
#define _Included_uk_ac_manchester_tornado_drivers_spirv_levelzero_LevelZeroDevice
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     uk_ac_manchester_tornado_drivers_spirv_levelzero_LevelZeroDevice
 * Method:    zeDeviceGetProperties_native
 * Signature: (JLuk/ac/manchester/tornado/drivers/spirv/levelzero/ZeDeviceProperties;)I
 */
JNIEXPORT jint JNICALL Java_uk_ac_manchester_tornado_drivers_spirv_levelzero_LevelZeroDevice_zeDeviceGetProperties_1native
        (JNIEnv *, jobject, jlong, jobject);

/*
 * Class:     uk_ac_manchester_tornado_drivers_spirv_levelzero_LevelZeroDevice
 * Method:    zeDeviceGetComputeProperties
 * Signature: (JLuk/ac/manchester/tornado/drivers/spirv/levelzero/ZeComputeProperties;)I
 */
JNIEXPORT jint JNICALL Java_uk_ac_manchester_tornado_drivers_spirv_levelzero_LevelZeroDevice_zeDeviceGetComputeProperties
        (JNIEnv *, jobject, jlong, jobject);

/*
 * Class:     uk_ac_manchester_tornado_drivers_spirv_levelzero_LevelZeroDevice
 * Method:    zeDeviceGetImageProperties
 * Signature: (JLuk/ac/manchester/tornado/drivers/spirv/levelzero/ZeDeviceImageProperties;)I
 */
JNIEXPORT jint JNICALL Java_uk_ac_manchester_tornado_drivers_spirv_levelzero_LevelZeroDevice_zeDeviceGetImageProperties
        (JNIEnv *, jobject, jlong, jobject);

/*
 * Class:     uk_ac_manchester_tornado_drivers_spirv_levelzero_LevelZeroDevice
 * Method:    zeDeviceGetMemoryProperties_native
 * Signature: (J[I[Luk/ac/manchester/tornado/drivers/spirv/levelzero/ZeMemoryProperties;)I
 */
JNIEXPORT jint JNICALL Java_uk_ac_manchester_tornado_drivers_spirv_levelzero_LevelZeroDevice_zeDeviceGetMemoryProperties_1native
        (JNIEnv *, jobject, jlong, jintArray, jobjectArray);

/*
 * Class:     uk_ac_manchester_tornado_drivers_spirv_levelzero_LevelZeroDevice
 * Method:    zeDeviceGetMemoryAccessProperties
 * Signature: (JLuk/ac/manchester/tornado/drivers/spirv/levelzero/ZeMemoryAccessProperties;)I
 */
JNIEXPORT jint JNICALL Java_uk_ac_manchester_tornado_drivers_spirv_levelzero_LevelZeroDevice_zeDeviceGetMemoryAccessProperties
        (JNIEnv *, jobject, jlong, jobject);

/*
 * Class:     uk_ac_manchester_tornado_drivers_spirv_levelzero_LevelZeroDevice
 * Method:    zeDeviceGetCacheProperties_native
 * Signature: (J[I[Luk/ac/manchester/tornado/drivers/spirv/levelzero/ZeDeviceCacheProperties;)I
 */
JNIEXPORT jint JNICALL Java_uk_ac_manchester_tornado_drivers_spirv_levelzero_LevelZeroDevice_zeDeviceGetCacheProperties_1native
        (JNIEnv *, jobject, jlong, jintArray, jobjectArray);

/*
 * Class:     uk_ac_manchester_tornado_drivers_spirv_levelzero_LevelZeroDevice
 * Method:    zeDeviceGetCommandQueueGroupProperties_native
 * Signature: (J[I[Luk/ac/manchester/tornado/drivers/spirv/levelzero/ZeCommandQueueGroupProperties;)I
 */
JNIEXPORT jint JNICALL Java_uk_ac_manchester_tornado_drivers_spirv_levelzero_LevelZeroDevice_zeDeviceGetCommandQueueGroupProperties_1native
        (JNIEnv *, jobject, jlong, jintArray, jobjectArray);

#ifdef __cplusplus
}
#endif
#endif
