/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class uk_ac_manchester_tornado_drivers_spirv_levelzero_LevelZeroBinaryModule */

#ifndef _Included_uk_ac_manchester_tornado_drivers_spirv_levelzero_LevelZeroBinaryModule
#define _Included_uk_ac_manchester_tornado_drivers_spirv_levelzero_LevelZeroBinaryModule
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     uk_ac_manchester_tornado_drivers_spirv_levelzero_LevelZeroBinaryModule
 * Method:    readBinary_native
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_uk_ac_manchester_tornado_drivers_spirv_levelzero_LevelZeroBinaryModule_readBinary_1native
        (JNIEnv *, jobject);

#ifdef __cplusplus
}
#endif
#endif
