/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class uk_ac_manchester_tornado_drivers_spirv_levelzero_LevelZeroFence */

#ifndef _Included_uk_ac_manchester_tornado_drivers_spirv_levelzero_LevelZeroFence
#define _Included_uk_ac_manchester_tornado_drivers_spirv_levelzero_LevelZeroFence
#ifdef __cplusplus
extern "C" {
#endif

/*
 * Class:     uk_ac_manchester_tornado_drivers_spirv_levelzero_LevelZeroFence
 * Method:    zeFenceCreate_native
 * Signature: (JLuk/ac/manchester/tornado/drivers/spirv/levelzero/ZeFenceDesc;Luk/ac/manchester/tornado/drivers/spirv/levelzero/ZeFenceHandle;)I
*/
JNIEXPORT jint JNICALL Java_uk_ac_manchester_tornado_drivers_spirv_levelzero_LevelZeroFence_zeFenceCreate_1native
    (JNIEnv *, jobject, jlong, jobject, jobject);

/*
 * Class:     uk_ac_manchester_tornado_drivers_spirv_levelzero_LevelZeroFence
 * Method:    zeFenceHostSynchronize_native
 * Signature: (JJ)I
 */
    JNIEXPORT jint JNICALL Java_uk_ac_manchester_tornado_drivers_spirv_levelzero_LevelZeroFence_zeFenceHostSynchronize_1native
    (JNIEnv *, jobject, jlong, jlong);

/*
 * Class:     uk_ac_manchester_tornado_drivers_spirv_levelzero_LevelZeroFence
 * Method:    zeFenceReset_native
 * Signature: (J)I
*/
JNIEXPORT jint JNICALL Java_uk_ac_manchester_tornado_drivers_spirv_levelzero_LevelZeroFence_zeFenceReset_1native
    (JNIEnv *, jobject, jlong);

#ifdef __cplusplus
}
#endif
#endif