/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class uk_ac_manchester_tornado_drivers_spirv_levelzero_LevelZeroDriver */

#ifndef _Included_uk_ac_manchester_tornado_drivers_spirv_levelzero_LevelZeroDriver
#define _Included_uk_ac_manchester_tornado_drivers_spirv_levelzero_LevelZeroDriver
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     uk_ac_manchester_tornado_drivers_spirv_levelzero_LevelZeroDriver
 * Method:    zeInit
 * Signature: (I)I
 */
JNIEXPORT jint JNICALL Java_uk_ac_manchester_tornado_drivers_spirv_levelzero_LevelZeroDriver_zeInit
        (JNIEnv *, jobject, jint);

/*
 * Class:     uk_ac_manchester_tornado_drivers_spirv_levelzero_LevelZeroDriver
 * Method:    zeDriverGet_native
 * Signature: ([I[J)I
 */
JNIEXPORT jint JNICALL Java_uk_ac_manchester_tornado_drivers_spirv_levelzero_LevelZeroDriver_zeDriverGet_1native
        (JNIEnv *, jobject, jintArray, jlongArray);

/*
 * Class:     uk_ac_manchester_tornado_drivers_spirv_levelzero_LevelZeroDriver
 * Method:    zeDeviceGet
 * Signature: (J[ILuk/ac/manchester/tornado/drivers/spirv/levelzero/ZeDevicesHandle;)I
 */
JNIEXPORT jint JNICALL Java_uk_ac_manchester_tornado_drivers_spirv_levelzero_LevelZeroDriver_zeDeviceGet
        (JNIEnv *, jobject, jlong, jintArray, jobject);

/*
 * Class:     uk_ac_manchester_tornado_drivers_spirv_levelzero_LevelZeroDriver
 * Method:    zeDriverGetProperties
 * Signature: (JLuk/ac/manchester/tornado/drivers/spirv/levelzero/ZeDriverProperties;)I
 */
JNIEXPORT jint JNICALL Java_uk_ac_manchester_tornado_drivers_spirv_levelzero_LevelZeroDriver_zeDriverGetProperties
        (JNIEnv *, jobject, jlong, jobject);

/*
 * Class:     uk_ac_manchester_tornado_drivers_spirv_levelzero_LevelZeroDriver
 * Method:    zeDriverGetApiVersion
 * Signature: (JLuk/ac/manchester/tornado/drivers/spirv/levelzero/ZeAPIVersion;)I
 */
JNIEXPORT jint JNICALL Java_uk_ac_manchester_tornado_drivers_spirv_levelzero_LevelZeroDriver_zeDriverGetApiVersion
        (JNIEnv *, jobject, jlong, jobject);

/*
 * Class:     uk_ac_manchester_tornado_drivers_spirv_levelzero_LevelZeroDriver
 * Method:    zeContextDestroy
 * Signature: (J)I
 */
JNIEXPORT jint JNICALL Java_uk_ac_manchester_tornado_drivers_spirv_levelzero_LevelZeroDriver_zeContextDestroy
        (JNIEnv *, jobject, jlong);

#ifdef __cplusplus
}
#endif
#endif
