/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class uk_ac_manchester_tornado_drivers_spirv_levelzero_LevelZeroModule */

#ifndef _Included_uk_ac_manchester_tornado_drivers_spirv_levelzero_LevelZeroModule
#define _Included_uk_ac_manchester_tornado_drivers_spirv_levelzero_LevelZeroModule
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     uk_ac_manchester_tornado_drivers_spirv_levelzero_LevelZeroModule
 * Method:    zeModuleBuildLogDestroy
 * Signature: (Luk/ac/manchester/tornado/drivers/spirv/levelzero/ZeBuildLogHandle;)I
 */
JNIEXPORT jint JNICALL Java_uk_ac_manchester_tornado_drivers_spirv_levelzero_LevelZeroModule_zeModuleBuildLogDestroy
        (JNIEnv *, jobject, jobject);

/*
 * Class:     uk_ac_manchester_tornado_drivers_spirv_levelzero_LevelZeroModule
 * Method:    zeKernelCreate_native
 * Signature: (JLuk/ac/manchester/tornado/drivers/spirv/levelzero/ZeKernelDesc;Luk/ac/manchester/tornado/drivers/spirv/levelzero/ZeKernelHandle;)I
 */
JNIEXPORT jint JNICALL Java_uk_ac_manchester_tornado_drivers_spirv_levelzero_LevelZeroModule_zeKernelCreate_1native
        (JNIEnv *, jobject, jlong, jobject, jobject);

#ifdef __cplusplus
}
#endif
#endif
