/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class uk_ac_manchester_tornado_drivers_spirv_levelzero_LevelZeroCommandQueue */

#ifndef _Included_uk_ac_manchester_tornado_drivers_spirv_levelzero_LevelZeroCommandQueue
#define _Included_uk_ac_manchester_tornado_drivers_spirv_levelzero_LevelZeroCommandQueue
#ifdef __cplusplus
extern "C" {
#endif

/*
 * Class:     uk_ac_manchester_tornado_drivers_spirv_levelzero_LevelZeroCommandQueue
 * Method:    zeCommandQueueExecuteCommandLists_native
 * Signature: (JILuk/ac/manchester/tornado/drivers/spirv/levelzero/ZeCommandListHandle;J)I
*/
JNIEXPORT jint JNICALL Java_uk_ac_manchester_tornado_drivers_spirv_levelzero_LevelZeroCommandQueue_zeCommandQueueExecuteCommandLists_1native
    (JNIEnv *, jobject, jlong, jint, jobject, jlong);

/*
 * Class:     uk_ac_manchester_tornado_drivers_spirv_levelzero_LevelZeroCommandQueue
 * Method:    zeCommandQueueSynchronize_native
 * Signature: (JJ)I
 */
JNIEXPORT jint JNICALL Java_uk_ac_manchester_tornado_drivers_spirv_levelzero_LevelZeroCommandQueue_zeCommandQueueSynchronize_1native
        (JNIEnv *, jobject, jlong, jlong);

#ifdef __cplusplus
}
#endif
#endif